import { beforeEach,it,expect,vi } from 'vitest';
const mocks=vi.hoisted(()=>({create:vi.fn(),delete:vi.fn(),execute:vi.fn(),upload:vi.fn(),list:vi.fn(),get:vi.fn()}));
vi.mock('@daytona/sdk',()=>({Daytona:class{create=mocks.create;delete=mocks.delete;get=mocks.get;snapshot={list:mocks.list};}}));
import { renderInDaytona } from '../lib/daytona/client';
const sandbox={id:'sandbox-test',process:{executeCommand:mocks.execute},fs:{uploadFile:mocks.upload}};
function success(){mocks.execute.mockResolvedValueOnce({exitCode:0,result:JSON.stringify({modulePath:'/usr/node_modules/playwright/index.js',chromium:'/usr/bin/chromium'})}).mockResolvedValueOnce({exitCode:0,result:''}).mockResolvedValueOnce({exitCode:0,result:JSON.stringify({title:'Real page fixture',url:'https://example.com/',canonicalUrl:null,text:'Example Domain',links:[]})});}
beforeEach(()=>{vi.resetAllMocks();process.env.DAYTONA_API_KEY='test';mocks.list.mockResolvedValue({items:[{name:'opportunity-worker',state:'active'}]});mocks.create.mockResolvedValue(sandbox);mocks.delete.mockResolvedValue(undefined);mocks.upload.mockResolvedValue(undefined);});
it('awaits deletion after success; labels and sandbox env exclude app secrets',async()=>{success();const result=await renderInDaytona('https://example.com/',()=>{});expect(result.text).toBe('Example Domain');expect(mocks.delete).toHaveBeenCalledWith(sandbox,60,true);expect(mocks.create.mock.calls[0][0].labels).toMatchObject({project:'deadline',run:'interactive'});expect(Object.keys(mocks.create.mock.calls[0][0].envVars)).toEqual(['TARGET_URL']);});
it('defer owns successful cleanup',async()=>{success();let cleanup:(()=>Promise<void>)|undefined;await renderInDaytona('https://example.com/',()=>{},task=>{cleanup=task;});expect(mocks.delete).not.toHaveBeenCalled();await cleanup!();expect(mocks.delete).toHaveBeenCalledTimes(1);});
it('worker failure deletes before throwing even with defer',async()=>{mocks.execute.mockResolvedValueOnce({exitCode:0,result:JSON.stringify({modulePath:'/node_modules/playwright/index.js',chromium:'/usr/bin/chromium'})}).mockResolvedValueOnce({exitCode:0}).mockResolvedValueOnce({exitCode:1,result:'error'});const defer=vi.fn();await expect(renderInDaytona('https://example.com/',()=>{},defer)).rejects.toThrow();expect(mocks.delete).toHaveBeenCalledTimes(1);expect(defer).not.toHaveBeenCalled();});
it('thrown timeout deletes',async()=>{mocks.execute.mockRejectedValue(new Error('TimeoutError'));await expect(renderInDaytona('https://example.com/',()=>{})).rejects.toThrow();expect(mocks.delete).toHaveBeenCalledTimes(1);});
it('cleanup failure keeps the successful result',async()=>{success();mocks.delete.mockRejectedValue(new Error('private provider detail'));expect((await renderInDaytona('https://example.com/',()=>{})).text).toBe('Example Domain');});
it('orphan filter rejects unlabeled, recent and invalid dates',async()=>{
 const {isOrphan}=await import('../scripts/orphans.mjs');const old=new Date(Date.now()-20*60000).toISOString();expect(isOrphan({createdAt:old})).toBe(false);expect(isOrphan({labels:{project:'other'},createdAt:old})).toBe(false);expect(isOrphan({labels:{project:'deadline'},createdAt:old})).toBe(true);expect(isOrphan({labels:{project:'deadline'},createdAt:new Date().toISOString()})).toBe(false);expect(isOrphan({labels:{project:'deadline'},createdAt:'invalid'})).toBe(false);
});
