import type { OpportunityResult } from '../lib/schema';
import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import { database,installation,event,result,sub } from './helpers';
import { saveOpportunity,saveSubscription,getOpportunity } from '../lib/db/repository';
import { checkOpportunity,hashText } from '../lib/monitor/check';
import { history,monitoring,review } from '../lib/monitor/repository';
import { compareResults } from '../lib/monitor/compare';
import { extractText } from '../lib/openai/extract-text';
import { fetchSource } from '../lib/agent/orchestrator';
import { groundResult } from '../lib/agent/grounding';
import { computeConfidence } from '../lib/agent/confidence';
import { automaticReminders } from '../lib/dates';
import { monitorTick } from '../lib/monitor/tick';
import webpush from 'web-push';
vi.mock('../lib/openai/extract-text',()=>({extractText:vi.fn()}));
vi.mock('../lib/agent/orchestrator',async importOriginal=>({...await importOriginal<typeof import('../lib/agent/orchestrator')>(),fetchSource:vi.fn()}));
vi.mock('web-push',()=>({default:{sendNotification:vi.fn()}}));
let d:Awaited<ReturnType<typeof database>>,i:string,id:string;
const old=():OpportunityResult=>({...structuredClone(result),importantDates:[{...result.importantDates[0],label:'Application deadline',value:'2030-10-05',precision:'date_only' as const,yearResolution:'explicit' as const,sourceText:'Application deadline October 5, 2030'}],requirements:[],conflicts:[],applicationUrl:null});
const next=()=>({...old(),importantDates:[{...old().importantDates[0],value:'2030-10-12',sourceText:'Application deadline October 12, 2030'}]});
function fixture(r=old(),text=r.importantDates.map(d=>d.sourceText).join(' ')){const source={url:r.sources[0].url,title:r.title,canonicalUrl:null,text,links:[],method:'plain fetch' as const};vi.mocked(fetchSource).mockResolvedValue(source);vi.mocked(extractText).mockResolvedValue(r);return source;}
async function due(){await d.db.query("UPDATE opportunities SET next_check_at=now()-interval '1 second',last_checked_at=now()-interval '11 minutes',lease_until=NULL WHERE id=$1",[id]);}
beforeEach(async()=>{vi.clearAllMocks();process.env.VAPID_PUBLIC_KEY='public';process.env.VAPID_PRIVATE_KEY='private';process.env.VAPID_SUBJECT='mailto:test@example.com';vi.mocked(webpush.sendNotification).mockResolvedValue({statusCode:201,body:'',headers:{}});d=await database();i=await installation(d.db);id=(await saveOpportunity(d.db,i,event({dueAt:'2030-10-05'}),old()))!.id;await monitoring(d.db,i,id,true,'daily');fixture();});
afterEach(async()=>{await d.pg.close();});
describe('monitoring with real SQL',()=>{
 it('baseline and unchanged make one then zero extraction calls',async()=>{await checkOpportunity(i,id,{db:d.db});vi.mocked(extractText).mockClear();await due();expect((await checkOpportunity(i,id,{db:d.db})).status).toBe('unchanged');expect(extractText).toHaveBeenCalledTimes(0);expect(webpush.sendNotification).toHaveBeenCalledTimes(0);});
 it('equivalent changed text and label-only variation create no changes',async()=>{await checkOpportunity(i,id,{db:d.db});await due();const r=old();r.importantDates[0].label='Registration deadline';fixture(r,r.importantDates[0].sourceText+' Updated footer');expect((await checkOpportunity(i,id,{db:d.db})).changes).toBe(0);expect((await history(d.db,i,id)).changes).toHaveLength(0);expect(webpush.sendNotification).toHaveBeenCalledTimes(0);});
 it('changed deadline creates one review, two device pushes, no duplicate; accept replaces reminders',async()=>{await saveSubscription(d.db,i,sub());await saveSubscription(d.db,i,sub(2));await checkOpportunity(i,id,{db:d.db});await due();fixture(next());expect((await checkOpportunity(i,id,{db:d.db})).changes).toBe(1);expect(webpush.sendNotification).toHaveBeenCalledTimes(2);expect((await getOpportunity(d.db,i,id))!.due_at).toBe('2030-10-05');const h=await history(d.db,i,id);expect(h.changes).toHaveLength(1);await due();await checkOpportunity(i,id,{db:d.db});expect(webpush.sendNotification).toHaveBeenCalledTimes(2);await review(d.db,i,String(h.changes[0].id),true);expect((await getOpportunity(d.db,i,id))!.due_at).toBe('2030-10-12');const reminders=(await d.db.query<{at:Date}>('SELECT at FROM reminders WHERE opportunity_id=$1 AND sent_at IS NULL',[id])).rows;expect(reminders.map(r=>new Date(r.at).toISOString())).toEqual(['2030-10-09T00:00:00.000Z','2030-10-11T00:00:00.000Z']);await monitorTick(d.db,Date.now()+20000);expect(webpush.sendNotification).toHaveBeenCalledTimes(2);});
 it('accept rolls back the result and reminder deletion when insertion fails',async()=>{await checkOpportunity(i,id,{db:d.db});await due();fixture(next());await checkOpportunity(i,id,{db:d.db});const change=String((await history(d.db,i,id)).changes[0].id);
 const broken:typeof d.db={...d.db,tx:fn=>d.db.tx(tx=>fn({...tx,query:async(sql,params)=>{if(sql.startsWith('INSERT INTO reminders'))throw new Error('simulated write failure');return tx.query(sql,params);}}))};
 await expect(review(broken,i,change,true)).rejects.toThrow();expect((await getOpportunity(d.db,i,id))!.due_at).toBe('2030-10-05');expect((await d.db.query('SELECT * FROM reminders WHERE opportunity_id=$1',[id])).rows).toHaveLength(1);expect((await history(d.db,i,id)).changes[0].status).toBe('pending_review');});
 it('dismiss preserves accepted dates and reminders',async()=>{await checkOpportunity(i,id,{db:d.db});await due();fixture(next());await checkOpportunity(i,id,{db:d.db});const h=await history(d.db,i,id);await review(d.db,i,String(h.changes[0].id),false);expect((await getOpportunity(d.db,i,id))!.due_at).toBe('2030-10-05');expect((await d.db.query('SELECT * FROM reminders WHERE opportunity_id=$1',[id])).rows).toHaveLength(1);});
 it('legacy baseline creates review without push',async()=>{await d.db.query('UPDATE opportunities SET accepted_result=NULL WHERE id=$1',[id]);await saveSubscription(d.db,i,sub());await checkOpportunity(i,id,{db:d.db});expect((await history(d.db,i,id)).changes[0].change_type).toBe('baseline_review');expect(webpush.sendNotification).not.toHaveBeenCalled();expect((await getOpportunity(d.db,i,id))!.accepted_result).toBeNull();});
 it('lease excludes a second claim, expired lease allows it; third failure resets cycle',async()=>{await d.db.query("UPDATE opportunities SET lease_until=now()+interval '6 minutes' WHERE id=$1",[id]);await expect(checkOpportunity(i,id,{db:d.db})).rejects.toMatchObject({status:409});vi.mocked(fetchSource).mockRejectedValue(new Error('private provider error'));for(let n=0;n<3;n++){await due();expect((await checkOpportunity(i,id,{db:d.db})).status).toBe('failed');}const o=await getOpportunity(d.db,i,id);expect(o!.attempt_count).toBe(0);expect(new Date(o!.next_check_at!).getTime()-Date.now()).toBeGreaterThan(23*3600000);expect(o!.accepted_result).toEqual(old());expect((await d.db.query('SELECT * FROM reminders WHERE opportunity_id=$1',[id])).rows).toHaveLength(1);expect((await history(d.db,i,id)).checks).toHaveLength(3);});
 it('manual check rate limit and posters rejected',async()=>{await checkOpportunity(i,id,{db:d.db});await expect(checkOpportunity(i,id,{db:d.db,manual:true})).rejects.toMatchObject({status:429});await d.db.query("UPDATE opportunities SET source_url='urn:poster:sha256:test' WHERE id=$1",[id]);await expect(checkOpportunity(i,id,{db:d.db})).rejects.toMatchObject({status:400});});
 it('other installations cannot read, toggle, check, accept or dismiss',async()=>{const b=await installation(d.db);await checkOpportunity(i,id,{db:d.db});await due();fixture(next());await checkOpportunity(i,id,{db:d.db});const c=String((await history(d.db,i,id)).changes[0].id);expect(await getOpportunity(d.db,b,id)).toBeNull();for(const action of [()=>history(d.db,b,id),()=>monitoring(d.db,b,id,true,'daily'),()=>checkOpportunity(b,id,{db:d.db}),()=>review(d.db,b,c,true),()=>review(d.db,b,c,false)])await expect(action()).rejects.toMatchObject({status:404});});
});
describe('comparison and grounding guards',()=>{
 it('omitted quote still present cannot remove a deadline',()=>{const r=old();r.importantDates=[];expect(compareResults(old(),r,old().importantDates[0].sourceText).changes).toHaveLength(0);});
 it('removal without rolling evidence never invents rolling',()=>{const r=old();r.importantDates=[];const c=compareResults(old(),r,'No dates').changes;expect(c.map(v=>v.type)).toEqual(['deadline_removed']);});
 it('both old and new quotes make conflict, not move',()=>{expect(compareResults(old(),next(),old().importantDates[0].sourceText+' '+next().importantDates[0].sourceText).changes.map(c=>c.type)).toEqual(['conflict_appeared']);});
 it('ambiguous fingerprints send no invented match; inferred year only history',()=>{const r=next();r.importantDates.push({...r.importantDates[0],sourceText:'Another quote'});expect(compareResults(old(),r,'Another quote').changes).toHaveLength(0);const inferred=next();inferred.importantDates[0].yearResolution='inferred_next_occurrence';expect(compareResults(old(),inferred,inferred.importantDates[0].sourceText).changes).toHaveLength(0);});
 it('grounding drops absent quotes, preserves event kind and gives inferred year low confidence',()=>{const r=old();const source=fixture(r,'Other text');expect(groundResult(r,source).result.importantDates).toHaveLength(0);r.importantDates[0].kind='event_start';r.importantDates[0].yearResolution='inferred_next_occurrence';source.text=r.importantDates[0].sourceText;const grounded=groundResult(r,source);expect(grounded.result.importantDates[0].kind).toBe('event_start');expect(computeConfidence(grounded.result,source.url,grounded.dropped,grounded.weak)).toBe('low');});
 it('hash normalizes whitespace and timezone reminders preserve wall clock through DST',()=>{expect(hashText('a  b')).toBe(hashText('a b'));const date={...old().importantDates[0],value:'2030-03-11'};expect(automaticReminders(date,'America/New_York').map(r=>r.at)).toEqual(['2030-03-08T14:00:00.000Z','2030-03-10T13:00:00.000Z']);});
});
