import { z } from "zod";
import { ImportantDate,OpportunityResult } from "@/lib/schema";
// Required nullable context is compatible with strict Structured Outputs; old public records stay unchanged.
export const EvidenceDate=ImportantDate.extend({yearContextText:z.string().nullable(),visibleYears:z.array(z.number().int())});
export const ExtractionDraft=OpportunityResult.extend({importantDates:z.array(EvidenceDate)});
export function extractionSchema(simplified:boolean){return simplified?ExtractionDraft.extend({importantDates:z.array(EvidenceDate.extend({sourceUrl:z.string()})),applicationUrl:z.string().nullable(),sources:z.array(OpportunityResult.shape.sources.element.extend({url:z.string()})),conflicts:z.array(OpportunityResult.shape.conflicts.element.extend({sourceUrls:z.array(z.string())}))}):ExtractionDraft;}
export const dateEvidenceInstructions=`For each date return yearContextText (a separate short verbatim passage containing contextual years, or null) and visibleYears (all four-digit years in that passage, or []). Keep sourceText and yearContextText verbatim in the original language, never concatenate distant passages or translate them. Use only the selected dominant poster/opportunity, never a neighboring poster, background sign, footer copyright, or unrelated listing. Include conflicting contextual years rather than hiding them. Every listed visibleYears item must appear in yearContextText. For web extraction yearContextText must be an exact substring of the supplied source slice.
Visible years may be four digits or two digits (26.09.27, 26-09-27, 26/09/27). Preserve them exactly; the validator checks year, month and day. Yearless month/day dates require unambiguous contextual evidence. A yearless range end may inherit its explicitly dated start's year and cross December into January. Never choose the computer's year to fill a gap. Weekday errors are uncertainty signals, not grounds for inventing another date.
Application periods (모집기간, 접수기간, 지원기간, 신청기간, 원서접수, 서류접수, application period/window/dates, registration period, applications open, apply between) produce application_open at the range start and deadline at its end. Event ranges produce event_start/event_end; interviews, judging and announcements are not application deadlines. Both endpoints may quote the same exact range. Keep generated labels in English.`;
